schema_version = "1.0.0"
id = "archpath"
version = "1.0.0"
name = "ArchPath"
tagline = "ArchPath"
maintainer = "Your Name"
type = "add-on"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]